/** Web-local aliases over the shared feed contract package. */
import type {
  AttentionItem,
  AppSessionStateResponse,
  AppSessionSyncState,
  AppSessionUser,
  DashboardBriefing,
  DashboardResponse,
  DashboardProfile,
  FeedResponse,
  FirstRunImportJobResponse,
  GmailThreadRow,
  GmailThreadSection,
  GmailThreadUpdate,
  GmailViewResponse,
  GoogleAuthState,
  AuthMeResponse,
  AuthUserResponse,
  MailboxLabel,
  MailboxResponse,
  MobileSessionExchangeRequest,
  MobileSessionExchangeResponse,
  MailboxSyncStateResponse,
  MailboxSyncTriggerResponse,
  PostLoginReadinessResponse,
  ThreadMessage,
  ThreadReaderResponse,
  TimingBand,
} from '@electronic-mail/types';

export type FeedItem = AttentionItem;
export type PrimaryActionType = AttentionItem['primary_action'];

export type {
  AppSessionStateResponse,
  AppSessionSyncState,
  AppSessionUser,
  DashboardBriefing,
  DashboardProfile,
  DashboardResponse,
  FeedResponse,
  FirstRunImportJobResponse,
  GmailThreadRow,
  GmailThreadSection,
  GmailThreadUpdate,
  GmailViewResponse,
  GoogleAuthState,
  AuthMeResponse,
  AuthUserResponse,
  MailboxLabel,
  MailboxResponse,
  MobileSessionExchangeRequest,
  MobileSessionExchangeResponse,
  MailboxSyncStateResponse,
  MailboxSyncTriggerResponse,
  PostLoginReadinessResponse,
  ThreadMessage,
  ThreadReaderResponse,
  TimingBand,
};
